# Generated by Django 4.2.7 on 2023-11-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_berita_publikasi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='berita',
            old_name='penulis',
            new_name='namapenulis',
        ),
        migrations.AddField(
            model_name='berita',
            name='gambarpenulis',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='berita',
            name='tanggal',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
