# Generated by Django 4.2.7 on 2023-11-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_rename_penulis_berita_namapenulis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='kategoriID',
            field=models.IntegerField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='berita',
            name='status',
            field=models.CharField(choices=[('publish', 'publish'), ('draft', 'draft')], max_length=200, null=True),
        ),
    ]
