# Generated by Django 4.2.7 on 2023-11-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_berita_kategoriid_berita_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='isi2',
            field=models.CharField(max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='berita',
            name='isi3',
            field=models.CharField(max_length=9999, null=True),
        ),
    ]
