# Generated by Django 4.2.7 on 2023-11-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_berita_isi2_berita_isi3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='kategoriID',
            field=models.IntegerField(null=True),
        ),
    ]
